### ISSUE TITLE
Nitpick: broken link in https://docs.rs/sharded-slab landing page.

### ISSUE THREAD

**Issue by vcfxb** [hawkw/sharded-slab#96]
The docs.rs page references the `Slab` type at https://docs.rs/sharded-slab/0.1.7/src/sharded_slab/lib.rs.html#19 but this actually brings me to the `loom` crate (I suspect due to `slab` being linked to the crate at https://docs.rs/sharded-slab/0.1.7/src/sharded_slab/lib.rs.html#137).

**Comment by hawkw** [comment]
Whoops, thanks for the report. We should fix that!

**Comment by vcfxb** [comment]
Closing, as this is fixed by #70 I believe.
